import type { shortestPath } from "./lib/dijkstra.d.ts";
import type { Edge, Graph } from "./lib/graph";
import type { stronglyConnectedComponents } from "./lib/kosaraju";

// This graph is about as large as TS can handle
type g = Graph.of<
	[
		// 1
		Edge<"A", "B", 45>,
		Edge<"B", "C", 67>,
		Edge<"C", "D", 23>,
		Edge<"D", "E", 89>,
		Edge<"I", "R", 28>,
		Edge<"E", "F", 12>,
		Edge<"F", "G", 56>,
		Edge<"H", "R", 6>,
		Edge<"G", "H", 34>,
		Edge<"H", "I", 78>,
		Edge<"B", "D", 73>,
		Edge<"C", "E", 18>,
		Edge<"C", "M", 81>,
		Edge<"E", "G", 37>,
		Edge<"G", "S", 70>,
		Edge<"G", "I", 44>,
		Edge<"H", "A", 29>,
		Edge<"I", "B", 76>,
		Edge<"H", "O", 19>,
		Edge<"B", "S", 19>,
		Edge<"A", "E", 85>,
		Edge<"B", "F", 38>,
		Edge<"C", "P", 86>,
		Edge<"C", "G", 64>,
		Edge<"D", "H", 51>,
		Edge<"E", "I", 22>,
		Edge<"F", "A", 77>,
		Edge<"C", "S", 90>,
		Edge<"G", "B", 49>,
		Edge<"F", "Y", 5>,
		Edge<"H", "C", 66>,
		Edge<"D", "M", 7>,
		Edge<"I", "D", 33>,
		Edge<"I", "J", 94>,
		// 2
		Edge<"J", "K", 52>,
		Edge<"K", "L", 17>,
		Edge<"L", "M", 79>,
		Edge<"M", "N", 43>,
		Edge<"J", "Z", 39>,
		Edge<"P", "Q", 91>,
		Edge<"Q", "J", 36>,
		Edge<"J", "L", 58>,
		Edge<"L", "R", 82>,
		Edge<"K", "M", 74>,
		Edge<"L", "N", 31>,
		Edge<"M", "O", 87>,
		Edge<"N", "P", 19>,
		Edge<"O", "Q", 62>,
		Edge<"J", "X", 2>,
		Edge<"Q", "T", 20>,
		Edge<"P", "J", 48>,
		Edge<"Q", "K", 39>,
		Edge<"N", "U", 12>,
		Edge<"J", "M", 71>,
		Edge<"K", "N", 54>,
		Edge<"L", "O", 26>,
		Edge<"M", "P", 80>,
		Edge<"K", "Y", 10>,
		Edge<"N", "Q", 47>,
		Edge<"P", "K", 42>,
		Edge<"O", "K", 9>,
		Edge<"Q", "L", 83>,
		Edge<"J", "N", 21>,
		Edge<"K", "O", 75>,
		Edge<"Q", "R", 11>,
		// 3
		Edge<"R", "S", 53>,
		Edge<"Z", "U", 3>,
		Edge<"T", "U", 69>,
		Edge<"U", "V", 40>,
		Edge<"W", "X", 35>,
		Edge<"X", "Y", 57>,
		Edge<"U", "W", 8>,
		Edge<"Y", "Z", 24>,
		Edge<"Z", "R", 72>,
		Edge<"R", "T", 15>,
		Edge<"T", "V", 50>,
		Edge<"U", "W", 63>,
		Edge<"V", "X", 27>,
		Edge<"S", "X", 6>,
		Edge<"W", "Y", 84>,
		Edge<"X", "Z", 32>,
		Edge<"Y", "R", 70>,
		Edge<"R", "X", 7>,
		Edge<"Z", "S", 46>,
		Edge<"R", "U", 77>,
		Edge<"S", "V", 13>,
		Edge<"T", "W", 60>,
		Edge<"W", "Z", 31>,
		Edge<"U", "X", 37>,
		Edge<"V", "Y", 82>,
		Edge<"W", "Z", 20>,
		Edge<"X", "R", 74>,
		Edge<"Y", "S", 39>,
	]
>;

type _dijkstra = shortestPath<"A", "Z", g>;
type _kosaraju = stronglyConnectedComponents<g>;
