import type { shortestPath } from "./lib/dijkstra";
import type { Edge, Graph } from "./lib/graph";

// This graph is about as large as TS can handle
type graph = Graph.of<
	[
		Edge.of<"A", "B", 64>,
		Edge.of<"A", "F", 47>,
		Edge.of<"A", "M", 30>,
		Edge.of<"A", "P", 54>,
		Edge.of<"B", "C", 16>,
		Edge.of<"B", "D", 35>,
		Edge.of<"B", "N", 41>,
		Edge.of<"B", "A", 22>,
		Edge.of<"C", "D", 9>,
		Edge.of<"C", "E", 16>,
		Edge.of<"C", "O", 71>,
		Edge.of<"C", "B", 72>,
		Edge.of<"D", "E", 38>,
		Edge.of<"D", "F", 42>,
		Edge.of<"D", "P", 10>,
		Edge.of<"D", "C", 67>,
		Edge.of<"E", "F", 87>,
		Edge.of<"E", "G", 11>,
		Edge.of<"E", "Q", 6>,
		Edge.of<"E", "D", 3>,
		Edge.of<"F", "G", 22>,
		Edge.of<"F", "H", 91>,
		Edge.of<"F", "R", 73>,
		Edge.of<"F", "E", 5>,
		Edge.of<"G", "H", 40>,
		Edge.of<"G", "I", 20>,
		Edge.of<"G", "S", 51>,
		Edge.of<"G", "F", 13>,
		Edge.of<"H", "I", 23>,
		Edge.of<"H", "J", 70>,
		Edge.of<"H", "T", 55>,
		Edge.of<"H", "G", 97>,
		Edge.of<"I", "J", 45>,
		Edge.of<"I", "K", 72>,
		Edge.of<"I", "U", 43>,
		Edge.of<"I", "H", 54>,
		Edge.of<"J", "K", 40>,
		Edge.of<"J", "L", 40>,
		Edge.of<"J", "V", 65>,
		Edge.of<"J", "I", 52>,
		Edge.of<"K", "L", 69>,
		Edge.of<"K", "M", 46>,
		Edge.of<"K", "W", 74>,
		Edge.of<"K", "J", 24>,
		Edge.of<"L", "M", 11>,
		Edge.of<"L", "N", 42>,
		Edge.of<"L", "X", 31>,
		Edge.of<"L", "K", 87>,
		Edge.of<"M", "N", 83>,
		Edge.of<"M", "O", 57>,
		Edge.of<"M", "Y", 85>,
		Edge.of<"M", "L", 55>,
		Edge.of<"N", "O", 99>,
		Edge.of<"N", "P", 99>,
		Edge.of<"N", "Z", 2>,
		Edge.of<"N", "M", 87>,
		Edge.of<"O", "P", 45>,
		Edge.of<"O", "Q", 77>,
		Edge.of<"O", "A", 18>,
		Edge.of<"O", "N", 51>,
		Edge.of<"P", "Q", 94>,
		Edge.of<"P", "R", 14>,
		Edge.of<"P", "B", 4>,
		Edge.of<"P", "O", 34>,
		Edge.of<"Q", "R", 12>,
		Edge.of<"Q", "S", 17>,
		Edge.of<"Q", "C", 17>,
		Edge.of<"Q", "P", 28>,
		Edge.of<"R", "S", 15>,
		Edge.of<"R", "T", 96>,
		Edge.of<"R", "D", 16>,
		Edge.of<"R", "Q", 37>,
		Edge.of<"S", "T", 18>,
		Edge.of<"S", "U", 60>,
		Edge.of<"S", "E", 13>,
	]
>;

type _az = shortestPath<"A", "Z", graph>;
